version: "3.9"
services:
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./config:/etc/prometheus
            - ./data:/prometheus
        entrypoint: ["/bin/prometheus"]
        command: ["--config.file=/etc/prometheus/prometheus.yml",
                  "--storage.tsdb.path=/prometheus",
                  "--web.console.libraries=/usr/share/prometheus/console_libraries",
                  "--web.console.templates=/usr/share/prometheus/consoles" ]

    grafana:
        image: grafana/grafana-enterprise
        ports:
            - "3000:3000"
        volumes:
            - ./grafana-storage:/var/lib/grafana
        environment:
            - no_proxy=localhost,127.0.0.1,prometheus
            - NO_PROXY=localhost,127.0.0.1,prometheus

    node1:
        image: prom/node-exporter
        ports:
            - "8080:9100"
    node2:
        image: prom/node-exporter
        ports:
            - "8081:9100"
    node3:
        image: prom/node-exporter
        ports:
            - "8082:9100"



